#Question3
dataset<-read.csv("singapore.economy.csv", header = TRUE)
na.omit(dataset)
attach(dataset)
plot(time, gdp, main = "Singapore GDP growth", xlab = "Time", ylab = "GDP(%)")
lm1 = lm(gdp~period)
 summary(lm1)
pairs(~gdp + exp + epg + hpr + gdpus + oil + crd + bci, dataset)
lm2  = lm(gdp~exp)
summary(lm2)
lm3= lm(gdp~exp + epg + hpr + oil + gdpus + crd)
summary(lm3)
quantile(gdp, probs = 0.05, na.rm = TRUE)
(dataset[,"gdp"] < -2.508209)
state<- ifelse((dataset[,"gdp"] <= -2.508209),"Crisis","Normal")
dataset<-data.frame(gdp,period,bci,state, check.names = TRUE, fix.empty.names = TRUE,stringsAsFactors = TRUE)
View(dataset)
period1 = (period <= 2) 
glm1 = glm(state~bci, data= dataset, family=binomial,subset = period1)
summary(glm1)
library(lattice)
library(ggplot2)
library(caret)
confusionMatrix(state,bci,positive = "1")
